// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgslRG5W-GxXA4lob8AWjWzfVN8QJpEC4',
    appId: '1:63051921428:web:e355e9f9bc71cd1cb78f01',
    messagingSenderId: '63051921428',
    projectId: 'streamapp-63342',
    authDomain: 'streamapp-63342.firebaseapp.com',
    storageBucket: 'streamapp-63342.firebasestorage.app',
    measurementId: 'G-HC92255FN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDryaGaJIKm7902OnvzNDzTOUpIbq56IkY',
    appId: '1:63051921428:android:3677fd42a966a920b78f01',
    messagingSenderId: '63051921428',
    projectId: 'streamapp-63342',
    storageBucket: 'streamapp-63342.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrCNFlM9najnQqqDJatLeiuZj1SOeQJaE',
    appId: '1:63051921428:ios:18fd7affc237af51b78f01',
    messagingSenderId: '63051921428',
    projectId: 'streamapp-63342',
    storageBucket: 'streamapp-63342.firebasestorage.app',
    iosBundleId: 'com.example.streamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrCNFlM9najnQqqDJatLeiuZj1SOeQJaE',
    appId: '1:63051921428:ios:18fd7affc237af51b78f01',
    messagingSenderId: '63051921428',
    projectId: 'streamapp-63342',
    storageBucket: 'streamapp-63342.firebasestorage.app',
    iosBundleId: 'com.example.streamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgslRG5W-GxXA4lob8AWjWzfVN8QJpEC4',
    appId: '1:63051921428:web:497cada58ea86317b78f01',
    messagingSenderId: '63051921428',
    projectId: 'streamapp-63342',
    authDomain: 'streamapp-63342.firebaseapp.com',
    storageBucket: 'streamapp-63342.firebasestorage.app',
    measurementId: 'G-B19XHR37L0',
  );
}
